import type { Metadata } from "next";
import "./globals.css";

import { Patrick_Hand } from "next/font/google";

const patrick = Patrick_Hand({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-patrick",
});
export const metadata: Metadata = {
  title: "Pritish",
  description: "Generated by create next app",
  icons: '/nagumooo.jpg'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${patrick.variable} ${patrick.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
